apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-backups
  labels:
    app.kubernetes.io/component: mysql-backups
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  capacity:
    storage: 20Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
{{ toYaml .Values.efs.mountOptions | indent 4 }}
  nfs:
    server: {{ .Values.efs.server }}
    path: {{ .Values.efs.backupPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-backups
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laravel.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql-backups
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  selector:
    matchLabels:
      app.kubernetes.io/component: mysql-backups
