{{- $data := .Values.sealedSecrets.ghcrPullSecret.encryptedData }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encryptedData:
    .dockerconfigjson: {{ required "sealedSecrets.ghcrPullSecret.encryptedData..dockerconfigjson is required" (index $data ".dockerconfigjson") | quote }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: ghcr-pull-secret
      namespace: {{ .Release.Namespace }}
    type: kubernetes.io/dockerconfigjson
