---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: app
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encryptedData:
    .dockerconfigjson: AgAmJilinB5lpjkZ2wBxRtcpheAo6kJ7qbXESdEoZfKXYbGTXykOwsLunNbXyU1F4reBR2Vle/joljsODQiB1KSsAOfxws3DsofqeGWhTglMXXsmtSkX+caWXopxjIbwDjzTSm/rVD7dIg0od0rCcc8Pur3Lt7yt96EAo4dcDNtk/tA4hTTZZ7ia2JDiNZKtUpY6Fy1YXjj8aycVrZyDbQkf7MLf6Xm3Gh6NezTsqcveyO8woVflSibprqPQecPo8J928pBGQNLq9KJ0747yMIsSntUgt0TxOFAR98M3OK4w5SDGkJGDhn3Io8lop5dSA85Iar8g5vgOUtXKrHByg9Cxm/KgQfHSO4ye2fnOXJ9Jpvnl6ENP9rus0InbeSr8y5lvhlvk+FgKR6zroMb6ykIgr3uMklkLiofx86mkw7njfTIsoGdoZ8TNkD4CKeviNX/JLz0gY6RxkhtWDJdSBaxtOvDftSMb/8dTgYZ4c5d6yxjGAcfx6ii0VhH3UsE9MRMfdAaSz+8c1DXVMibWDUm0tRoQrvr99kRxHhTMbn+sVL6zz+IkNgLDECd86m+XHW+LtEJmc2veB762xtbRm/jE6QJR11WSUOSUVqkCjNlUQLetziIxyVG/4rLfOedPT6F/Zt1rhdwZscPfDztVjJ9mUUqT5Mi5vUkwsMetmk/+VwC0aPVw8DoGD9dRzzaMC6fmGm+AQTDVURPcdkbNSw3q+BnXU2MxyUWWVxGsLNI0mRcxGG/TFhFqnSQsxhxd7plGcOEALqQn2ERtfYO7P6jBflEjwKwx65VNdn1pK7wPR56vtkbHx7Pvi/gRuENWtlV82qZqs9/aUb+EF2VtR4q2ExuwP+gMIUk6h2WdR1Q1gc4ehcmf5yh7nKG1roMovU4PDyT7FXwrJipwjq5rgMpkRE9w5JQIYyJJrA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: ghcr-pull-secret
      namespace: app
    type: kubernetes.io/dockerconfigjson
