apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "laravel.fullname" . }}-migrate
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "argocd.argoproj.io/hook": PreSync
    "argocd.argoproj.io/sync-wave": "-1"
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        {{- include "laravel.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
        {{- end }}
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["php", "artisan", "migrate", "--force"]
          envFrom:
            - configMapRef:
                name: {{ include "laravel.fullname" . }}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.passwordKey }}
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: app-key
