{{- $data := .Values.sealedSecrets.mysqlCredentials.encryptedData }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-credentials
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encryptedData:
    app-key: {{ required "sealedSecrets.mysqlCredentials.encryptedData.app-key is required" (index $data "app-key") | quote }}
    mysql-password: {{ required "sealedSecrets.mysqlCredentials.encryptedData.mysql-password is required" (index $data "mysql-password") | quote }}
    mysql-root-password: {{ required "sealedSecrets.mysqlCredentials.encryptedData.mysql-root-password is required" (index $data "mysql-root-password") | quote }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: mysql-credentials
      namespace: {{ .Release.Namespace }}
    type: Opaque
