replicaCount: 2
mysql:
  primary:
    persistence:
      selector:
        matchLabels:
          app.kubernetes.io/component: mysql-data
sealedSecrets:
  mysqlCredentials:
    encryptedData:
      app-key: prod-placeholder
      mysql-password: prod-placeholder
      mysql-root-password: prod-placeholder
  ghcrPullSecret:
    encryptedData:
      .dockerconfigjson: prod-placeholder

